language: python

python:
  - "2.7"
  - "3.4"

env:
  matrix:
    - REQ='django>=1.8, <1.9'
    - REQ='django>=1.9, <1.10'
    - REQ='django>=1.10, <1.11'
    - REQ='django>=1.11, <2.0'
    - REQ='django>=2.0, <2.1'
matrix:
  allow-failures:
  exclude:
    - python: '2.7'
      env: REQ='django>=2.0, <2.1'

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install .
  - pip install $REQ
  - pip install -r test_requirements.txt

# command to run tests
script: python manage.py test
